# name: Deploy HTML to Remote Server

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Copy HTML via SCP
#         uses: appleboy/scp-action@v0.1.3
#         with:
#           host: ${{ secrets.SERVER_IP }}
#           username: dev
#           key: ${{ secrets.SSH_KEY }}
#           source: "index.html"
#           target: "/var/www/web"

name: Deploy HTML to Server

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH and deploy files
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          #Trust the server host key
          ssh-keyscan -p 25552 ssh.tekhqs.net >> ~/.ssh/known_hosts

          # Deploy index.html to the server
          scp -P 25552 ./index.html sara@ssh.tekhqs.net:/var/www/html/
