name: Deploy HTML to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy HTML via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: dev
          key: ${{ secrets.SSH_KEY }}
          source: "index.html"
          target: "/var/www/web"

